### ISSUE TITLE
Need to run the Images

### ISSUE THREAD

**Issue by mstruser** [dimasukr/mstr-docker#3]
Hello,
Thank you so much for the webinar and the help you provided for creating these images.
I could build the images using the code you provided, but not sure how I would run these images as I do not have the docker compose file you used to run this, could you please provide the file or suggest an alternative way to run these images as containers.

Thanks,
Alok

**Comment by fas3r** [comment]
Hello @mstruser, 

are you doing the setup over SSH ? I'm having trouble during the setup ... 

I tried to active Xforward and change few setting in the scripts which execute the setup but I can not get around it.

Thank you by advance.

**Comment by mstruser** [comment]
Hello @fas3r ,
Yes I am trying to do this over SSH.I am trying to run this complete setup as instructed by @dimasukr , I could create all the images but while running them as container, I could only run the postgre one, others are not running. I am particularly confused about the image 'gcxi' which @dimasukr  used in the docker compose file.
I am not sure what image is this, could you please help if you have an idea about this.

Thanks,
Alok

**Comment by fas3r** [comment]
Hello @dimasukr ,

Did you change anything to make it work over ssh ?

If I ask that's because I get and I'm kind of stuck even if I understand the error ... : 


Checking file integrity.......done.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833)
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at javax.swing.JOptionPane.showInputDialog(JOptionPane.java:576)
	at com.microstrategy.install.core.Controller.languageSelector(Controller.java:319)
	at com.microstrategy.install.core.Controller.initWizard(Controller.java:100)
	at com.microstrategy.install.core.Controller.main(Controller.java:96)
	... 5 more
